### ISSUE TITLE
TypeError: Cannot read property 'failureType' of null

### ISSUE THREAD

**Issue by BTexier** [dubocr/overkiz-client#2]
Bonjour,

Tout d'abord, merci pour le beau plug-in Tahoma.
Malheureusement et depuis quelque temps maintenant, j'ai cette erreur qui pop après une exécution d'une automatisation.

`01/09/2021, 07:02:02 TypeError: Cannot read property 'failureType' of null
    at Execution.onStateUpdate (/hoobs/node_modules/overkiz-client/src/models/Execution.ts:54:19)
    at Timeout._onTimeout (/hoobs/node_modules/overkiz-client/src/Client.ts:207:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

Ce qui cause un arrêt total de mon Homebridge.

Avez-vous déjà rencontré ce problème ?
Merci d'avance

**Comment by davidbonan** [comment]
#4
